import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose.multiplatform)
}

kotlin {
    jvm()

    sourceSets {
        jvmMain.dependencies {
            implementation(project(":shared"))
            implementation(compose.desktop.currentOs)
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(libs.koin.core)
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.athena.reader.MainKt"

        nativeDistributions {
            // This is what produces the .deb and the .exe you asked for.
            targetFormats(TargetFormat.Deb, TargetFormat.Exe, TargetFormat.Dmg)
            packageName = "project-athena"
            packageVersion = "0.1.0"
            description = "A free online library on nostr — the library of Athena, rebuilt"
            vendor = "Athena"

            // Icons are generated by tools/make-icons.py, and are deliberately
            // not tracked. Setting them unconditionally would make packaging
            // fail on a fresh clone with a confusing "file doesn't exist" —
            // jpackage falls back to a default icon perfectly well.
            val linuxIcon = project.file("icons/icon.png")
            val windowsIcon = project.file("icons/icon.ico")

            linux {
                debMaintainer = "you@example.org"
                menuGroup = "Education"
                if (linuxIcon.exists()) iconFile.set(linuxIcon)
            }

            windows {
                menuGroup = "Project Athena"
                upgradeUuid = "6f3a1c92-5b47-4d18-9e2a-71c0d4b8e5f3"
                if (windowsIcon.exists()) iconFile.set(windowsIcon)
            }

            macOS {
                // Apple's pkg/dmg versioning requires MAJOR > 0, so 0.x.y
                // (our actual app version) isn't a legal value here.
                dmgPackageVersion = "1.0.0"
            }
        }
    }
}
